### ISSUE TITLE
Does not work when other than the first array entry matches

### ISSUE THREAD

**Issue by janober** [deitch/searchjs#6] opened 2015-12-27 10:03 UTC
Hope everything is going well!

So if I have for example data like this:
{name:"Alice",age:30, email: ["alice@searchjs.com","alice@gmail.com"], cars: [{brand: 'BMW', cds: [{title:'Best Of 2015'}, {title:'Best Of 2016'}]}, {brand: 'Porsche'}]}

I can not find it with this search:
{"cars.cds.title":"Best Of 2016"}

The fix for the issue can be found here:
https://github.com/janober/searchjs/commit/ef94e35a4de3f4971fe6290558ce71363849b4fa

**Comment by deitch** [comment] 2015-12-27 10:35
So you are saying `{"cars.cds.title":"Best of 2015"}` would work, but the problem is because it needs to match the second (or later) entry?

**Comment by deitch** [comment] 2015-12-27 10:36
Love it. You even added the right tests! Can you close this issue, and turn it into a pull request?

**Comment by janober** [comment] 2015-12-27 10:46
Sure but did not do it initially because there are always a lot of other change in there that Webstorm does automatically. However here is one.
https://github.com/deitch/searchjs/pull/7

**Comment by deitch** [comment] 2015-12-27 10:53
That's OK. Even if I do not automatically pull, it creates a much better record... and sometimes the changes are enough to convince me to change styling. :-)

**Comment by deitch** [comment] 2015-12-27 10:58
Fixed per the PR.

**Closed by deitch** 2015-12-27 10:58 UTC

**Comment by janober** [comment] 2015-12-27 11:26
Great thanks, that was fast.

Then already happy new year!

**Comment by deitch** [comment] 2015-12-27 12:27
Heh, I have things sitting in my inbox for far too long. When something like this comes along, and with a great fix and tests to boot, more than happy to carve out time to make it through. So thank you.

Happy New Year!
